const express = require('express')
const categoryRouter = require('./categoryRoutes')
const bookRouter = require('./bookRoutes')
const userRouter = require('./userRoutes')
const authRouter = require('./authRoutes')
const cartRouter = require('./cartRoutes')
const reviewRouter = require('./reviewRoutes')
const orderRouter = require('./orderRoutes')
const notifyRouter = require('./notifyRoutes')
const chatRouter = require('./chatRoutes')
const warehouseRouter = require('./warehouseRoutes')
const statsRouter = require('./statsRoutes')

const app = express()
app.use('/books', bookRouter)
app.use('/users', userRouter)
app.use('/categories', categoryRouter)
// app.use('/auth', authRouter)
app.use('/', authRouter)

app.use('/cart', cartRouter)
app.use('/reviews', reviewRouter)
app.use('/orders', orderRouter)
app.use('/notify', notifyRouter)
app.use('/chat', chatRouter)
app.use('/warehouse', warehouseRouter)
app.use('/stats', statsRouter)

module.exports = app
